### ISSUE TITLE
CustomTabsActivityLifecycleCallbacks for applications with multiple activites

### ISSUE THREAD

**Issue by conkur** [saschpe/android-customtabs#10]
Hello,

I'd like to register the CustomTabsActivityLifecycleCallbacks, but my application has two activities, one is the splash screen and one is the main activity. Is there a way that this callback can only do operations on a specified activity? I'd like to only use this for our main activity.

Thanks for the awesome library!

**Comment by saschpe** [comment]
I could provide another implementation based on the lifecycle library (https://developer.android.com/topic/libraries/architecture/lifecycle.html) but that would add another dependency. It would allow to pre-load only for specific activities but needs more setup in onCreate(). However, re-creating what the CustomTabsActivityLifecycleCallbacks does is simple:

```java
@Override
public void onCreate(Bundle savedInstanceState) {
    customTabsHelper = new CustomTabsHelper();
}
@Override
public void onResume() {
    customTabsHelper.bindCustomTabsService(activity);
}
@Override
public void onPause() {
    customTabsHelper.unbindCustomTabsService(activity);
}
```

**Comment by conkur** [comment]
Gotcha, recreating would be the way to go. Thanks for the help
