### ISSUE TITLE
Using customTabsSession when building the CustomTabsIntent

### ISSUE THREAD

**Issue by conkur** [saschpe/android-customtabs#11]
Hey there,

I noticed that when we're building the CustomTabsIntent, we're not passing in a session when `CustomTabsIntent.Builder` can take a `CustomTabsSession`.

Are we still getting the full benefits of the `warmup` without passing in the session?

Thanks

**Comment by saschpe** [comment]
You mean in the provided example application?

**Comment by tudorgk** [comment]
I think what @conkur is trying to say is that the library doesn't take advantage of the `session.mayLaunchUrl(uri, ..., ...)` which preloads the webpage and makes the custom-tabs worth using.

**Comment by saschpe** [comment]
The library doesn't stop you from doing either thing.
