### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by yesidlazaro** [saschpe/android-customtabs#3]
hey , thanks in advance i want to use your library but i getting this version when try to sync gradle 

> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.1.0) from [com.android.support:design:26.1.0] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:customtabs:26.0.2] AndroidManifest.xml:25:13-35 value=(26.0.2).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

**Comment by saschpe** [comment]
There are various ways to enforce a newer version of a dependency. You can force in gradle's resolution strategy or try tools: replace. It's not an issue here but a common thing when you have many dependencies
