### ISSUE TITLE
Hiding the title bar

### ISSUE THREAD

**Issue by tommytcchan** [saschpe/android-customtabs#9]
Hi there,
Is it possible in any way to hide the title bar? I want to have a somewhat native feel to the app. I read your code and there are no options to do so. 

Best,
T

**Comment by aradjdi** [comment]
+1

**Comment by kksal55** [comment]
+1

**Comment by saschpe** [comment]
This library exposes Google's CustomTabs functionality but I don't think this is supported: https://developer.chrome.com/multidevice/android/customtabs. "Native" feel comes by using the same colors and not leaving the app (i.e. it feels much faster). It's not a progressive web app though.
